### ISSUE TITLE
update_metadata fails updating pyproject.toml if not present

### ISSUE THREAD

**Issue by ptrebert** [core-unit-bioinformatics/cubi-tools#31]
The script fails because it seems to assume that `pyproject.toml` is present (which is not the case in a new repository):

```bash
Traceback (most recent call last):
  File "/home/ebertp/work/code/cubi/cubi-tools/cubi-tools/./update_metadata.py", line 263, in <module>
    main()
  File "/home/ebertp/work/code/cubi/cubi-tools/cubi-tools/./update_metadata.py", line 43, in main
    update_pyproject_toml(project_dir, ref_repo_wget)
  File "/home/ebertp/work/code/cubi/cubi-tools/cubi-tools/./update_metadata.py", line 203, in update_pyproject_toml
    version_old = toml.load(pathlib.Path(project_dir, f), _dict=dict)
  File "/home/ebertp/work/software/conda/lib/python3.9/site-packages/toml/decoder.py", line 133, in load
    with io.open(_getpath(f), encoding='utf-8') as ffile:
FileNotFoundError: [Errno 2] No such file or directory: 
```

**Comment by svenwillger** [comment]
Revised script from Sven B works without pyproject.toml being present; however, if pyproject.toml is missing it only gets downloaded (and modified) if any other file was altered.
Fix that!

**Comment by svenwillger** [comment]
The `pyproject.toml` is treated differently than the other metadata files. First there is now a check if that file is present. If not, it"ll be added to the project dir from the desired branch/version tag without further modification. If the file is present, it probably contains project specific information that should not be altered: therefore, only the cubi.metadata.version entry is getting updated if the versions differ.
